#!/usr/bin/env node
// Vendors icon artwork into src/icons/generated.ts.
//
// This is deliberately an extraction step, not a runtime dependency: the island
// loads only local path data, so a sandboxed or offline session can never trigger
// a fetch. Sources are local npm packages, licences noted in THIRD_PARTY_ICONS.md:
//
//   * lucide-static  — ISC — everyday UI glyphs (house, settings, check, …)
//   * simple-icons   — CC0-1.0 — brand marks (Claude, OpenCode, …)
//
// Run from apps/desktop-windows:  node tools/vendor-icons.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const LUCIDE = {
  house: "house",
  bubble: "messages-square",
  plus: "plus",
  gear: "settings",
  gearFill: "settings",
  speakerOn: "volume-2",
  speakerOff: "volume-x",
  arrowUpRight: "arrow-up-right",
  chevronRight: "chevron-right",
  chevronLeft: "chevron-left",
  check: "check",
  arrowUp: "arrow-up",
  bang: "circle-alert",
  xmark: "x",
  timer: "timer",
  ellipsis: "ellipsis",
  star: "star",
  terminal: "terminal",
  bolt: "zap",
  play: "play",
};

const BRANDS = {
  claude: "claude",
  claudecode: "claudecode",
  anthropic: "anthropic",
  opencode: "opencode",
};

function innerSvg(path) {
  const raw = readFileSync(path, "utf8");
  // lucide files carry an XML-side comment above <svg>, so anchor on it rather
  // than on the first `>` in the file.
  const start = raw.indexOf("<svg");
  const open = raw.indexOf(">", start);
  const close = raw.lastIndexOf("</svg>");
  if (start < 0 || open < 0 || close < 0) throw new Error(`not an svg: ${path}`);
  return raw
    .slice(open + 1, close)
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

const lucideOut = {};
for (const [name, icon] of Object.entries(LUCIDE)) {
  const path = join(root, "node_modules", "lucide-static", "icons", `${icon}.svg`);
  lucideOut[name] = innerSvg(path);
}

const brandOut = {};
for (const [name, icon] of Object.entries(BRANDS)) {
  const path = join(root, "node_modules", "simple-icons", "icons", `${icon}.svg`);
  brandOut[name] = innerSvg(path);
}

const header = `// GENERATED by tools/vendor-icons.mjs. Do not edit by hand.
// Vendored local artwork; licences: lucide ISC, simple-icons CC0-1.0.
// See THIRD_PARTY_ICONS.md at the repository root.

/** Inner SVG markup (path/shape elements), to be rendered inside a 24x24 viewBox. */
export interface VendoredIcon {
  /** True when the icon is drawn with strokes (lucide) rather than fills. */
  stroke: boolean;
  inner: string;
}
`;

const emit = (name, table, stroke) =>
  `export const ${name}: Record<string, VendoredIcon> = {
${Object.entries(table)
  .map(([k, v]) => `  ${JSON.stringify(k)}: { stroke: ${stroke}, inner: ${JSON.stringify(v)} },`)
  .join("\n")}
};
`;

writeFileSync(
  join(root, "src", "icons", "generated.ts"),
  `${header}\n${emit("LUCIDE", lucideOut, true)}\n${emit("BRANDS", brandOut, false)}\n`,
);
console.log("vendored", Object.keys(lucideOut).length, "lucide,", Object.keys(brandOut).length, "brand icons");
